Failure # 1 (occurred at 2025-01-28_18-49-06)
[36mray::PPO.train()[39m (pid=56460, ip=127.0.0.1, actor_id=8ecf138d5a94379573eb6eae01000000, repr=PPO)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 397, in train
    result = self.step()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 853, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 2838, in _run_one_training_iteration
    results = self.training_step()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 429, in training_step
    train_batch = synchronous_parallel_sample(
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 680, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 76, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(AttributeError): [36mray::RolloutWorker.apply()[39m (pid=56468, ip=127.0.0.1, actor_id=e5f8a09a9651e7b0d7c2f7e501000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x146af9e80>)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 185, in apply
    raise e
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 696, in sample
    batches = [self.input_reader.next()]
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 344, in run
    outputs = self.step()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 363, in step
    ) = self._base_env.poll()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 633, in poll
    ) = env_state.poll()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 828, in poll
    self.reset()
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 912, in reset
    raise e
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/env/multi_agent_env.py", line 906, in reset
    obs_and_infos = self.env.reset(seed=seed, options=options)
  File "/Users/leesg17/miniconda3/envs/pettingzoo/lib/python3.9/site-packages/ray/rllib/env/wrappers/multi_agent_env_compatibility.py", line 53, in reset
    infos = {k: {} for k in obs.keys()}
AttributeError: 'tuple' object has no attribute 'keys'
